# Generated by Django 5.2.1 on 2025-06-21 23:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classroom', '0001_initial'),
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('open_time', models.DateTimeField()),
                ('close_time', models.DateTimeField()),
                ('duration_minutes', models.PositiveIntegerField()),
                ('max_attempts', models.PositiveIntegerField(default=1)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('total_questions', models.PositiveIntegerField(default=0)),
                ('code', models.CharField(editable=False, max_length=8, unique=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='classroom.classroom')),
            ],
        ),
        migrations.CreateModel(
            name='ExamQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='exam.exam')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.question')),
            ],
            options={
                'ordering': ['position'],
                'unique_together': {('exam', 'question')},
            },
        ),
    ]
