# Generated by Django 5.2.1 on 2025-07-31 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='rate',
            field=models.CharField(choices=[('Dễ', 'Dễ'), ('Trung Bình', 'Trung Bình'), ('Khó', 'Khó')], default='Dễ', max_length=20, verbose_name='Độ khó'),
        ),
        migrations.AlterField(
            model_name='question',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
