# Generated by Django 5.2.1 on 2025-06-21 23:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exam', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.JSONField(default=dict)),
                ('backup_answers', models.JSONField(default=dict)),
                ('last_backup', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('student_answer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='score', to='answer.studentanswer')),
            ],
        ),
        migrations.CreateModel(
            name='StudentExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateTimeField(auto_now_add=True)),
                ('submit_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('in_process', 'Đang làm'), ('submitted', 'Đã nộp'), ('graded', 'Đã chấm điểm')], default='in_process', max_length=20)),
                ('attempt_number', models.PositiveIntegerField(default=1)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_exams', to='exam.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('student', 'exam', 'attempt_number')},
            },
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='student_exam',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='answer.studentexam'),
        ),
    ]
