# Generated by Django 5.2.1 on 2025-07-22 01:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentexam',
            name='join_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentexam',
            name='start_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentexam',
            name='status',
            field=models.CharField(choices=[('joined', 'Đã tham gia'), ('in_process', 'Đang làm'), ('submitted', 'Đã nộp')], default='joined', max_length=20),
        ),
    ]
