# Generated by Django 5.2.1 on 2025-06-21 23:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('close', 'Close'), ('wait', 'Coming soon')], max_length=10)),
                ('code', models.CharField(editable=False, max_length=8, unique=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('id_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClassroomStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('join_time', models.DateTimeField(auto_now_add=True)),
                ('id_classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='classroom.classroom')),
                ('id_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classrooms_joined', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('id_classroom', 'id_student')},
            },
        ),
    ]
